/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-29 04:56:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/EZENIC-166/Desktop/HyeongRae/ezen_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687741574536L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<title>Home</title>\n");
      out.write("	<script src=\"https://kit.fontawesome.com/e927512ef5.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("  	<link rel=\"stylesheet\" href=\"/resources/css/home.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- class logo는 좌측에 위치 사이즈는 작게 -->\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img src=\"/resources/img/rental.png\" alt=\"XXX\">\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <!-- id container는 화면 중앙 상단에 위치  -->\n");
      out.write("            <div id=\"container\"> <a href=\"\"><h1 class=\"style-3\">Web_Site_Name</h1></a></div>\n");
      out.write("            <div class=\"nav\">\n");
      out.write("                <div class=\"center-items\">\n");
      out.write("                    <a href=\"\"><p name=\"cname\" id=\"cname\">정수기</p></a>\n");
      out.write("                    <a href=\"\"><p name=\"cname\" id=\"cname\">비데</p></a>\n");
      out.write("                    <a href=\"\"><p name=\"cname\" id=\"cname\">공기청정기</p></a>\n");
      out.write("                    <a href=\"\"><p name=\"cname\" id=\"cname\">매트리스</p></a>\n");
      out.write("                </div>                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <br>\n");
      out.write("        <div class=\"info\">\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-user fa-xl\" style=\"color: black;\" onclick=\"toggleTooltip();\"></i>\n");
      out.write("            <div id=\"tooltip\" class=\"speech-bubble\">\n");
      out.write("               <a href=\"/user/signup\">회원가입</a> <br>\n");
      out.write("               <a href=\"/user/login\">로그인</a> <br> \n");
      out.write("               <a href=\"\">회원정보수정</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"search\">\n");
      out.write("            <span id=\"search\">\n");
      out.write("                <i class=\"fa-solid fa-magnifying-glass fa-xl\" style=\"color: black;\"></i>\n");
      out.write("            </span>\n");
      out.write("            <input id=\"search-input\" type=\"text\" placeholder=\"Search...\">\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <main>\n");
      out.write("        <div class=\"video-box\">\n");
      out.write("            <video src=\"/resources/video/production_id_4069110 (2160p).mp4\" muted autoplay loop>\n");
      out.write("                <source src=\"/video/production_id_4069110 (2160p).mp4\" type=\"video/mp4\">\n");
      out.write("            </video>\n");
      out.write("            <div class=\"video-box-btn\">\n");
      out.write("              <a href=\"\">CLICK ME</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"footer\">\n");
      out.write("            <div class=\"ft-logo\">\n");
      out.write("                <img src=\"/resources/img/images.png\" alt=\"\" width=\"50px\" height=\"50px\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footinfo\">\n");
      out.write("                <span><h6>©2023 Ok RENTAL. All Rights Reserved.</h6></span>\n");
      out.write("                <span><h6>RETURN POLICY</h6></span>\n");
      out.write("                <span><h6>TERMS & LEGAL</h6></span>\n");
      out.write("                <span><h6>PRIVACY NOTICE</h6></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footsns\">\n");
      out.write("           <a href=\"https://www.facebook.com/login/?locale=ko_KR\"><i class=\"fa-brands fa-facebook\" style=\"color: #000000;\"></i></a>\n");
      out.write("           <a href=\"https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoia28ifQ%3D%3D%22%7D\"><i class=\"fa-brands fa-twitter\" style=\"color: #000000;\"></i></a>\n");
      out.write("            <a href=\"https://www.instagram.com/\"><i class=\"fa-brands fa-instagram\" style=\"color: #000000;\"></i></a>\n");
      out.write("            <a href=\"https://github.com/login\"><i class=\"fa-brands fa-github\" style=\"color: #000000;\"></i></a>\n");
      out.write("            <a href=\"https://discord.com/login\"><i class=\"fa-brands fa-discord\" style=\"color: #000000;\"></i></a>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    <script src=\"/resources/js/home.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
